[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "schistosomiasis"
version = "0.1.0"
dependencies = [
    "gdal",
    "natcap.invest",
    "numpy",
    "pygeoprocessing",
    "taskgraph"
]